#!/usr/bin/env bash
# Bash script that will display information about subdomains


domain_config() {
	#domain attributes



	if [ $# -eq 2 ]; then

	    domain=$1
	    subdomain=$2
	    record_type=$(dig "$2.$1." | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $4 }')
   	    dest=$(dig "$2.$1." | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $5 }')
   	    echo "The subdomain $subdomain is a $record_type and points to $dest"

	else
	    array=( "www" "lb-01" "wed-01" "web-02" )
	    for n in "${array[@]}" ; do
		record=$(dig array[n]."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $4 }')
		destination=$(dig array[n]."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $5 }')
    		echo "The subdomain ${array[n]} is a $record record and points to $destination" 
    	    done
	fi
}

if [ "$#" == 2 ]; then
    domain_config "$1" "$2"
else
    domain_config "$1"
fi