#!/usr/bin/env bash
# Bash script that will display information about subdomains
domain=$1
subdomain=$2


domain_config() {
	#domain attributes



	if [ $# -eq 2 ]; then

	    record_type=$(dig "$2.$1." | grep -A1 'ANSWER SECTION:' | awk -F" " '{ print $4 }')
   	    dest=$(dig "$2.$1." | grep -A1 'ANSWER SECTION:' | awk -F" " '{ print $5 }')
   	    echo "The subdomain $subdomain is a ${record_type//[$'\t\r\n ']} record and points to ${dest//[$'\t\r\n ']}"

	else

	    www_recType=$(dig www."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $4 }')
	    www_dest=$(dig www."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $5 }')
    	    echo "The subdomain www is a ${www_recType//[$'\t\r\n ']} record and points to ${www_dest//[$'\t\r\n ']}"

	    lb_01_recType=$(dig lb-01."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $4 }')
            lb_01_dest=$(dig lb-01."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $5 }')
            echo "The subdomain lb-01 is a ${lb_01_recType//[$'\t\r\n ']} record and points to ${lb_01_dest//[$'\t\r\n ']}"

	    web_01_recType=$(dig web-01."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $4 }')
            web_01_dest=$(dig web-01."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $5 }')
            echo "The subdomain web-01 is a ${web_01_recType//[$'\t\r\n ']} record and points to ${web_01_dest//[$'\t\r\n ']}"

	    web_02_recType=$(dig web-02."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $4 }')
            web_02_dest=$(dig web-02."$domain" | grep -A1 'ANSWER SECTION:' | awk -F " " '{ print $5 }')
            echo "The subdomain web-02 is a ${web_02_recType//[$'\t\r\n ']} record and points to ${web_02_dest//[$'\t\r\n ']}"
	 fi
}

if [ "$#" == 2 ]; then
    domain_config "$1" "$2"
else
    domain_config "$1"
fi