#!/usr/bin/env bash
# FILEPATH= $FILEPATH
# IPADRESS= $IP
# USER= $USER
# PATHTOKEY= $PATHTOKEY
if [ $# -ne 4 ]; then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no "$FILEPATH" "$PATHTOKEY" "$USER@$IP:~/"
fi
