#!/usr/bin/env bash
# Install ngix on web server
sudo apt-get -y update
sudo apt-get -y install nginx
response=$(curl --write-out %{http_code} --silent --output /dev/null ubuntu@35.190.188.174)
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start