#!/usr/bin/env bash
# redirect new server
sudo apt-get -y update
sudo apt-get -y install nginx
redirect="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37i $redirect" /etc/nginx/sites-available/default
sudo service nginx restart