#!/usr/bin/env bash
# redirect new server
apt-get -y update
apt-get -y install nginx
sed -i "0,/localhost;/s/localhost;/localhost;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n/" /etc/nginx/sites-available/default
service nginx restart