#!/usr/bin/env bash
# redirect new server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "HolbertonSchool" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i s, 'location/ {','location/redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\n\t}';  
sudo service nginx restart