#!/usr/bin/env bash
# redirect new server 404 and 301 failure
sudo apt-get -y update
sudo apt-get -y install nginx
redirect="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37i $redirect" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/index.html
error_404="\\\terror_page 404 /404.html; \n\tlocation = 404.html {\n\t\troot /var/www/html/index.html;\n\t\tinternal;\n\t}"
sudo sed -i "41i $error_404" /etc/nginx/sites-available/default
sudo service nginx start