#!/usr/bin/env bash
# redirect new server 404 and 301 failure
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'HolbertonSchool' | sudo tee /usr/share/nginx/html/index.html
service nginx start
sudo sed -i "s,sever_name_;,\n\tlocation/redirect_me {\n\treturn 301 https://https://www.youtube.com/watch?v=WZ9W0nIonnM\n\t}";
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
error_404="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sudo sed -i "33i $error_404" /etc/nginx/sites-available/default
service nginx reload
service nginx restart