#!/usr/bin/env bash
# Configuring a server with specification response header
apt-get -y update
apt-get -y install nginx
sed -i "26i add_header X-Served-By \$hostname;\n" /etc/nginx/sites-enabled/default
service nginx restart