#!/usr/bin/env bash
# Install ans configure HAproxy on lb-01 server.
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get -y update
sudo apt-get -y install haproxy=1.5.\*
frontend mortonium.tech
         bind ./*:80
         stats enable
         stats uri /stats
         default_backend morton_back /etc/haproxy/haproxy.cfg

backend morton_back
        balance roundrobin
        mode http
        server 704-web-01 35.237.127.124
        server 704-web-02 34.74.215.227

service haproxy restart