#!/usr/bin/env bash
#configure server to listen to port 80 for all active IPv4 IPs
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx reload
