#!/usr/bin/env bash
#script create loop to be killed

#!/usr/bin/env bash
#script displays string indefinitely

trap "echo I am invincible!!!" SIGINT SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done
