#!/usr/bin/env bash
# Bash script that give info about a file

file="holbertonschool" #set varible equal to file name
if [ -e "$file" ]       #check if file exists
then
	echo "$file file exists."
else
	echo "$file file does not exist."
fi
if [ -s "$file" ]       #check if file is empty 
then
    echo "$file is not empty"
else
    echo "$file is empty"
fi
if [ -f "$file" ]       #check if file is a regular file
then
    echo "$file is a regular file"
else
    echo
fi
