#!/usr/bin/env bash
# Bash script that give info about a file
# Uses if -else statements

file="holbertonschool" #set varible equal to file name
if [ -e "$file" ]       #check if file exists
then
	echo "$file file exists."
    if [ -s "$file" ]       #check if file is empty 
    then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
fi
    if [ -f "$file" ]       #check if file is a regular file
    then 
        echo "$file is a regular file"
fi
else
    echo "$file file does not exist "
fi
