#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.

echo -e "127.0.02\tlocalhost"> ~/hosts.new
echo -e "8.8.8.8\tfacebook.com">> ~/hosts.new
cat /etc/hosts >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
