#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.

echo '127.0.02  localhost'> ~/hosts.new
echo '8.8.8.8 facebook.com'>> ~/hosts.new
cat /etc/hosts >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
