#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.


cp /etc/hosts ~/hosts.new | grep -vx '127.*localhost'/etc/hosts>/tmp/hangar
echo '127.0.02  localhost'> ~/hosts.new
echo '8.8.8.8 facebook.com'>> ~/hosts.new
cat /tmp/hangar>> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
