#!/usr/bin/env bash
#script to run another user as root
sudo chmod 755 /etc/nginx/nginx.conf
pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sed -i '/#user/c\user nginx;' /etc/nginx/nginx.conf
sudo sed -i -e 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
