#!/usr/bin/env bash
#script to run another user as root
pkill apache2
chmod o+r /etc/nginx/nginx.conf
sed -i '/#user/c\user nginx;' /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx nginx